### ISSUE TITLE
Error: add ListCondition - expect an array 

### ISSUE THREAD

**Issue by duynguyen0511** [gomoob/php-pushwoosh#11]
http://gomoob.github.io/php-pushwoosh/create-message.html

```php
$notification = Notification::create()
    ->addCondition(ListCondition::create('listCondition')->in('value 1', 'value 2', 'value 3'));
```

Should be

```php
$notification = Notification::create()
    ->addCondition(ListCondition::create('listCondition')->in(array('value 1', 'value 2', 'value 3')));
```

**Comment by bgaillard** [comment]
Hi @duynguyen0511 and so sorry to response sooooo late ! 

You're right their's an error in the documentation and it should be fixed, we'll do it https://github.com/gomoob/php-pushwoosh/milestones/1.0.5.
