### ISSUE TITLE
Add Better API Error Handling

### ISSUE THREAD

**Issue by vinkla** [gomoob/php-pushwoosh#13]
Today our premium subscription to pushwoosh ended. When we tried to push a message to the API it returned the following:
````php
array (size=3)
  'status_code' => int 210
  'status_message' => string 'This feature is available for Premium accounts only' (length=51)
  'response' => null
```

Though, the package didn't return the status message as an error. Instead it returned this:
```php
array_key_exists() expects parameter 2 to be array, null given

// Gomoob/Pushwoosh/Model/Response/CreateMessageResponse.php:43
if (array_key_exists('Messages', $json['response'])) {
```

Maybe we could implement a way to handle these kinds of status messages? What do you think?

**Comment by bgaillard** [comment]
Hi @vinkla and thanks for this suggestion, I agree with you the `CreateMessageResponse` class should check if `$json['response']` is `null`.

Perhaps this check is not specific to the `CreateMessageResponse` class and should be common to all kind of responses. 

> Maybe we could implement a way to handle these kinds of status messages? What do you think?

Yes sure, we'll try to do it but it seems to be a very minor issue so we'll certainly do it later (in few weeks or months). 

If you want to help you can provide a PR on this by taking into account the fact that the check to implement should be common to all responses if possible.

Thanks.

**Comment by vinkla** [comment]
Great! I think a global error handling would be better instead of just updating the `CreateMessageResponse` class. 

It is a minor issue since this library only works if you've an paid account. In my case, I had just upgraded my the account but the API returned this error anyway. Contacted the support and they said it usually takes up to a half hour before it kicks in.

Thanks for getting back. We're using your library in some of our projects and it works great.

**Comment by bgaillard** [comment]
Ok, happy to see the library feets your needs, feel free to publish more issues if you think about new features or improvements. 

> It is a minor issue since this library only works if you've an paid account. In my case, I had just upgraded my the account but the API returned this error anyway. Contacted the support and they said it usually takes up to a half hour before it kicks in.

Ok, perhaps this is an opportunity to augment error messages returned by Pushwoosh by providing additional help with the error (see #14).

**Comment by bgaillard** [comment]
Fixed with https://github.com/gomoob/php-pushwoosh/commit/941161ef4792355ad10f31bc2e4a45a456e650db.

**Comment by vinkla** [comment]
Well done!
