### ISSUE TITLE
The link to the library has been removed from the official documentation

### ISSUE THREAD

**Issue by bgaillard** [gomoob/php-pushwoosh#22]
Yesterday the Pushwoosh team published a new version of their documentation (http://docs.pushwoosh.com/docs/createmessage). The link to our library has been removed from this documentation. 

We should ask Pushwoosh to add the link back, or even better propose to the Pushwoosh team to add a php-pushwoosh tab in each PHP sample (we could write those samples).

**Comment by shaders** [comment]
done. :+1:  http://docs.pushwoosh.com/docs/createmessage

**Comment by bgaillard** [comment]
Great, thanks a lot @shaders ! 

I was also thinking to add a link for each operation, for example :
 * In the /createMessage section your docs add a link to http://gomoob.github.io/php-pushwoosh/create-message.html
 * In the /deleteMessage section of your docs add a link to http://gomoob.github.io/php-pushwoosh/delete-message.html
 * Etc.

Do you think it would be a good idea (we can edit the Pushwoosh documentation pages) ?

**Comment by shaders** [comment]
Done!

I see there's an option to "suggest edits" however I have no idea yet how it works on readme.io

**Comment by bgaillard** [comment]
Hi @shaders :+1: :+1: :+1:. 

Thanks, so I'm closing this issue.
