### ISSUE TITLE
Describe how to use the library without composer

### ISSUE THREAD

**Issue by bgaillard** [gomoob/php-pushwoosh#23]
Several users encounter difficulties to use the library without composer : 

 * http://stackoverflow.com/questions/30570744/how-to-install-and-use-php-pushwoosh-on-ubuntu-12-04-lts-linux-os-with-without-u
 * http://stackoverflow.com/questions/28599212/yii-struggle-with-setting-pushwoosh-php-lib-through-composer
 * http://stackoverflow.com/questions/30590074/is-it-required-to-include-any-files-from-gomoobphp-pushwooshto-to-run-a-php-pro

We should explain how to use the library without composer, a code sample will also help.

**Comment by corse-xx** [comment]
as requested: 

```
if (isset($_GET['doit3'])) {
	require(dirname(__DIR__).'/Gomoob/Pushwoosh/Client/Pushwoosh.php');

	print 'pushwoosh';
	try {
		$pushwoosh = Pushwoosh::create()
    	->setApplication('MY APP CODE HERE')
    	->setAuth('MY AUTH HERE');
	} catch(Exception $e) {
		print 'feck it';
		print $e->getMessage();
	}
	// Create a request for the '/createMessage' Web Service
	$request = CreateMessageRequest::create()
	    ->addNotification(Notification::create()->setContent('Hello Jean !'));

	// Call the REST Web Service
	$response = $pushwoosh->createMessage($request);

	// Check if its ok
	if($response->isOk()) {
	    print 'Great, my message has been sent !';
	} else {
	    print 'Oops, the sent failed :-('; 
	    print 'Status code : ' . $response->getStatusCode();
	    print 'Status message : ' . $response->getStatusMessage();
	}
}
```
And my folder structure is like the attached screenie. I know i've done something silly, but its Friday!
![folders](https://cloud.githubusercontent.com/assets/4817065/9275122/d4d1da2c-4292-11e5-9c41-27946ffb5ace.png)

**Comment by bgaillard** [comment]
Hi @corse-xx, 

Here is a code sample which works without composer. 

```php
<?php 

require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/ICURLClient.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/IPushwoosh.php';

require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Client/CURLClient.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Client/Pushwoosh.php';

require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Notification/ADM.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Notification/Android.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Notification/BlackBerry.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Notification/IOS.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Notification/Mac.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Notification/MinimizeLink.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Notification/Notification.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Notification/Platform.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Notification/Safari.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Notification/WNS.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Notification/WP.php';

require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Request/CreateMessageRequest.php';

require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Response/AbstractResponse.php';
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Response/CreateMessageResponse.php';

use Gomoob\Pushwoosh\Client\Pushwoosh;
use Gomoob\Pushwoosh\Model\Request\CreateMessageRequest;
use Gomoob\Pushwoosh\Model\Notification\Notification;

// Configure the Pushwoosh client
$pushwoosh = Pushwoosh::create()->setApplication('MY APP CODE HERE')->setAuth('MY AUTH HERE');

// Create a request for the '/createMessage' Web Service
$request = CreateMessageRequest::create()->addNotification(Notification::create()->setContent('Hello Jean !'));

// Call the REST Web Service
$response = $pushwoosh->createMessage($request);

// Check if its ok
if($response->isOk()) {
	print 'Great, my message has been sent !';
} else {
	print 'Oops, the sent failed :-(';
	print 'Status code : ' . $response->getStatusCode();
	print 'Status message : ' . $response->getStatusMessage();
}
```

The best advice I can give you is **ALWAYS USE COMPOSER IF YOU CAN !** : https://getcomposer.org. 

Anyway others have the same problems so I think I'll simply create a script which produces an `includes.php` file to be able to only do that if we do not have composer : 

```php
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/includes.php';

...
```

**Comment by corse-xx** [comment]
Hiya and thank you for the quick response. I implemented that but its not executing either. If i put a quick print statement like print 'here'; in before the require_once statements and then execute then i get nothing, but if i remove from the use statement on and execute then i get the print statement. Something is definitely happening within the namespace that is not being pushed back.

**Comment by bgaillard** [comment]
Strange, I think you have an error elsewhere or a configuration problem, in my opinion php-pushwoosh is not the cause of your problem here, perhaps ... 
 * You made a mistake elsewhere 
 * You use a very old PHP version, namespaces and use statements are supported since PHP 5.3 (http://php.net/manual/en/language.namespaces.importing.php). Our library is supported since PHP 5.3 (I cannot guaranty it is working with older PHP versions).

Also besides using `print` take the time to configure your PHP environment to write error logs inside a file, it will definitly help you.

**Comment by corse-xx** [comment]
I chucked the code up to a test server i have in the US to see if i got anything different (to be sure that PHP install wasn't causing an issue here) and eh voila i get an error message of:

Fatal error: Class 'Gomoob\Pushwoosh\Model\Response\CreateMessageResponseResponse' not found in /home/petsco10/beta.alonestaff.com/data/php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Response/CreateMessageResponse.php on line 40

**Comment by bgaillard** [comment]
:+1: Ok, so now check the file is their, check you have the right UNIX rights on your files and directories and you downloaded a not corruped zip https://github.com/gomoob/php-pushwoosh/archive/master.zip ;-).

**Comment by bgaillard** [comment]
Add do not forget to add this before the `CreateMessageResponse.php` require...
```php
require_once 'php-pushwoosh-master/src/main/php/Gomoob/Pushwoosh/Model/Response/CreateMessageResponseResponse.php';
```

**Comment by corse-xx** [comment]
was just the declaration :) all working now so its the local php and i really need to go shout at my environment creator :p thank you Baptiste!

**Comment by bgaillard** [comment]
Closing this because no serious PHP developer should use PHP without composer (or at least if absolutly needed this is absolutly not the responsibility of php-pushwoosh).
