### ISSUE TITLE
Add a .gitattributes file

### ISSUE THREAD

**Issue by bgaillard** [gomoob/php-pushwoosh#27]
See http://blog.madewithlove.be/post/gitattributes, this will allow users of the library to pull a lighten dist package and so improve download time.

**Comment by vinkla** [comment]
:+1:

**Comment by bgaillard** [comment]
Fixed with https://github.com/gomoob/php-pushwoosh/commit/3fe7bda2f2f3cccf159205adb41761a69e23be10.
