### ISSUE TITLE
Content is supposed to be string type only.

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [gomoob/php-pushwoosh#40]
For example here: https://github.com/gomoob/php-pushwoosh/blob/d482f3a4b33f26417baaaab5c6b6384cb8372efc/src/main/php/Gomoob/Pushwoosh/Model/Notification/Notification.php#L82
But [pushwoosh docs](http://docs.pushwoosh.com/docs/createmessage)  say it can be either an assoc array or a string:
> "content":{ // Object( language1: 'content1', language2: 'content2' ) OR string.

It would be nice if you update the related phpdocs.

**Comment by bgaillard** [comment]
Hi @AlexeyKupershtokh and thanks for this suggestion, i'll do it for the next release https://github.com/gomoob/php-pushwoosh/milestones/1.5.0. 

Do no hesitate to create a PR for this.

**Comment by bgaillard** [comment]
Fixed with https://github.com/gomoob/php-pushwoosh/commit/897d9ac4be61c2e36cbef474871770cdf723ebd4.
