### ISSUE TITLE
Internal Server Error and vendor folder

### ISSUE THREAD

**Issue by clewsk8er** [gomoob/php-pushwoosh#45]
I am using php-pushwoosh library and am getting an internal server error. I believe we may need to white list the ip but it seems it is constantly changing based on the server data. Also I find it strange that no folder/library was added to vendor for php-pushwoosh after installing it using composer. It shows when doing “php composer.phar show” but has no files it seems in the vendor folder. I was hoping you could help me figure out what I may need to do for this to work. Here is some screen shots of the afore mentioned instances. 

![vendor](https://cloud.githubusercontent.com/assets/9630142/14533236/41f08f36-0232-11e6-8a42-a039ac3ca1fd.png)

![terminal1](https://cloud.githubusercontent.com/assets/9630142/14533313/93a14d3e-0232-11e6-9a64-aebb3ad43fb5.png)

![error](https://cloud.githubusercontent.com/assets/9630142/14533252/4e5a4c12-0232-11e6-94e7-05a78239dedf.png)

**Comment by bgaillard** [comment]
Hi @clewsk8er, 

> I find it strange that no folder/library was added to vendor for php-pushwoosh after installing it using composer. 

Its strange, we use the library everyday on several machines Windows, Unix, etc... and have never encountered this issue. 

What version of the library areyou using ? Are you sure the folder is not their, did you refresh your folders (if you update your deps in the terminal and view your files in your IDE its possible the IDE did not saw the new files...) ?

Also could you provide the content of your {{composer.json}} files ?

**Comment by clewsk8er** [comment]
![composer](https://cloud.githubusercontent.com/assets/9630142/14536153/fd00f142-023e-11e6-86d8-91df1e0babfd.png)

**Comment by bgaillard** [comment]
Ok, you're problem is probably that you have 2 `require` in your `composer.json` file, it should be that instead.
```json
...
"require" : {
    "php" : ">=5.2.4",
    "mongodb/mongodb": "^1.0.0@beta",
    "gomoob/php-pushwoosh" : "~1.0"
}
...
```

**Comment by clewsk8er** [comment]
Ah ok awesome. Thank you very much. Do I simply run update or install now and it will add the library?

**Comment by bgaillard** [comment]
Both `update` or `install` will work. 

So I close this issue as its solved, happy coding with php-pushwoosh :smile:

**Comment by clewsk8er** [comment]
Ok, I am applying the fix now. Thank you so much for your time. Sorry I am such a newbie at composer.

**Comment by bgaillard** [comment]
@clewsk8er no problem always happy to help :-).
