### ISSUE TITLE
Hey from Pushwoosh!

### ISSUE THREAD

**Issue by FallDi** [gomoob/php-pushwoosh#53]
Hello!
Please remove minimize_link value 3(baidu).
It deprecated and removed.
Proof https://www.facebook.com/Pushwoosh/posts/756668594476249

**Comment by bgaillard** [comment]
Hi @FallDi, thanks for the info.

This will be in version `1.6.0`, see https://github.com/gomoob/php-pushwoosh/commit/97ee0c96b994bad3ac78f0d3d2d501e77b424945.
