### ISSUE TITLE
setCURLClient documentation wrong

### ISSUE THREAD

**Issue by fvermeulen** [gomoob/php-pushwoosh#65]
This line could be removed right or like the other method in that class you should return the instance. 

https://github.com/gomoob/php-pushwoosh/blob/master/src/main/php/Gomoob/Pushwoosh/Client/Pushwoosh.php#L303

**Comment by bgaillard** [comment]
Hi @fvermeulen and thanks for your response, you're right on this the code should return a reference to the Pushwoosh instance as documented. 

Can you create a PR for this ?

Thanks

**Comment by bgaillard** [comment]
Now the `setCURLClient(...)` method returns the instance so we can close this issue. This will be integrated in version `1.8.0`.
