### ISSUE TITLE
No DefaultTimeOut

### ISSUE THREAD

**Issue by fvermeulen** [gomoob/php-pushwoosh#66]
We found an issue, that in the [CurlClient](https://github.com/gomoob/php-pushwoosh/blob/master/src/main/php/Gomoob/Pushwoosh/Client/CURLClient.php#L62), you are using there is no default timeout-value set.
In our case the call got stuck.

- **CURLOPT_CONNECTTIMEOUT**

	The number of seconds to wait while trying to connect. Use 0 to wait indefinitely.

- **CURLOPT_TIMEOUT**

	The maximum number of seconds to allow cURL functions to execute.

[PHP curl_setopt doc](http://php.net/manual/en/function.curl-setopt.php)

**Comment by bgaillard** [comment]
Hi, you're right, in fact it seems other users as problems with this too but we did not have the time to fix it for now. 

Notes for @gomoob/employees 
* We should merge the PR proposed by @p-golovin first
* It seems others forked the repo to deal with the timeout problem reported here, https://github.com/robin-x/php-pushwoosh/commit/4b76d13a1ef302726517e658436f735bad1c4853

@fvermeulen we'll try to integrate this in version `1.8.0` of the library soon, thanks for reporting this.

**Comment by bgaillard** [comment]
We've added new functions to allow developers to add and overwrite the CURL option they want. This feature will be available in version `1.8.0`. So we can close this now.

**Comment by bgaillard** [comment]
Hi @fvermeulen, simple message to indicate you that it's now possible to change the CURL options in use in the library. 

You'll find details about how to do it here http://gomoob.github.io/php-pushwoosh/general-concepts.html.
