### ISSUE TITLE
Is this repo still maintained ?

### ISSUE THREAD

**Issue by jonathangreco** [gomoob/php-pushwoosh#74]
Hi, last updates was almost 3 years ago, is this package still working against pushwoosh API ?

**Comment by Xplouder** [comment]
Don't think so. I mean, it is working but not with all the features.
@bgaillard

**Comment by bgaillard** [comment]
Hi, we maintained this repository in the past but not anymore because our company Gomoob closed.

We'll not have time to maintain this repository so feel free to fork it and propose to the community an other place to maintain the project.
